---
- hosts: ubuntu_slaves
  become: true
  vars:
    NODEJS_VERSION: "18"
  tasks:
    - name: Install the gpg key for nodejs LTS
      apt_key:
        url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
        state: present
      when: ansible_distribution == "Ubuntu"
    
    - name: Install the nodejs LTS repos
      apt_repository:
        repo: "deb https://deb.nodesource.com/node_{{ NODEJS_VERSION }}.x {{ ansible_distribution_release }} main"
        state: present
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: Install the nodejs
      apt:
        name: nodejs
        state: present
      when: ansible_distribution == "Ubuntu"


- hosts: localhost
  become: true
  tasks:
    - name: hello 
      shell:
        cmd: curl -fsSL https://rpm.nodesource.com/setup_16.x | sudo bash -
        chdr: /tmp
      when: ansible_distribution == "Amazon"
